#pragma once

enum class BulletType {
	PEASHOOTER_BULLET,
	THREEPEATER_BULLET,
	TORCHWOOD_BULLET,

	MUSHROOM_BULLET,
	FUMESHROOM_BULLET,
	SEASHROOM_BULLET,
	CABBAGEPULT_BULLET,
	MELONPULT_BULLET,

	CACTUS_SPIKE,

	CHERRY_EXPLODE,
	POTATO_EXPLODE,
	DOOMSHROOM_EXPLODE,
	JALAPENO_EXPLODE,
	INVISIBLE_RECT
};