#pragma once

enum class BulletType {
	PEASHOOTER_BULLET,
	THREEPEATER_BULLET,
	TORCHWOOD_BULLET,

	MUSHSHROOM_BULLET,
	FUMESHROOM_BULLET,
	SEASHROOM_BULLET,
	MELONPULT_BULLET,

	CACTUS_SPIKE,

	CHERRY_EXPLODE,
	POTATO_EXPLODE,
	DOOMSHROOM_EXPLODE,
	INVISIBLE_RECT
};